device: 0
data:
  output_dir: "../config/examples/chinese_word_segmentation/CNN_CRF"
  data_dir: "../data/datasets/canton_ws"
  train: data_combined.json 
  dev: data_combined.json 
  test: data_combined.json 
text_prepro:
  steps:
    - full_to_half
eval:
  batch_size: 64
  model_file: "model.pt" # under output_dir / "model"
train:
  task: "chinese_word_segmentation"
  model_class: "CNN_CRF"
  seed: 42
  batch_size: 16
  final_model: "best" # or "last"
model_params:
  # ================= TDBERT =================
  num_train_epochs: 50
  embedding_trainable: True
  # tokenizer_name: "bert-base-chinese"  # source:::tokenizer_type "huggingface:::toastynews/electra-hongkongese-large-discriminator"   
  # pretrained_lm: "bert-base-chinese" # huggingface format "toastynews/electra-hongkongese-large-discriminator" 
  # ================= TGSAN =================
  # num_train_epochs: 50
  # pretrained_emb_path: "../data/word_embeddings/sgns.target.word-character.char1-2.dynwin5.thr10.neg5.dim300.iter5"
  # embedding_trainable: False
