## This file declares variables to be passed into your templates ##

# Below will be replaced by environment variables defined in env.sh
appName: "$APP_NAME"
imageRepository: "$IMAGE_REPOS"
imageTag: "$IMAGE_TAG"
ciBuildRef: "$CI_REF"

# Below set as Always or IfNotPresent
imagePullPolicy: Always

## A string to add extra environment variables
extraEnvVars: |
  - name: TZ
    value: "Asia/Hong_Kong"

# By default, no changes required for below service settings
service:
  enabled: true
  type: ClusterIP
  externalPort: 8080
  internalPort: 8080
replicaCount: 1

# Whether to enable ingress rule for external API access
ingress:
  enabled: true

# Whether to load all files under /configs into a Configmap
configmap:
  enabled: true
#  configfileMounts:
#    - mountTo: "/ailab/gunicorn_conf.py"
#      name: "gunicorn_conf.py"
#    # if there are multiple files that need to be used as configmap format
#    #- mountTo: "/ailab/app_conf.py"
#    #  name: "app_conf.py"


# Whether use imagePullSecrets or not (not need this var. with RnD env)
imagePullSecrets:
  - name: docker-pub

nodeSelector: {}

tolerations: []

affinity: {}

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 4000m
    memory: 8G
  requests:
    cpu: 4000m
    memory: 8G

# Whether to enable Horizontal Pod Autoscaler
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  cpu:
    averageUtilization: 75
  memory:
    averageUtilization: 75


# Whether to enable "istio-ingress" rule for external API access
istioingress:
  enabled: false
  internalPort: 8080

# Whether to enable "istio-auth" rule for external API access
# Istio authentication policy and related mutual TLS authentication
istioauth:
  enabled: false
  issuer: http://keycloak-http.playground/keycloak/auth/realms/realm-ess
  jwksUri: http://keycloak-http.playground/keycloak/auth/realms/realm-ess/protocol/openid-connect/certs
  mtls:
    mode: PERMISSIVE
  principalBinding: USE_ORIGIN

# Whether to enable "istio-destinationrule" rule for external API access
# https://archive.istio.io/v1.4/docs/concepts/traffic-management/#destination-rules
# Destination rules are applied after virtual service routing rules are evaluated, so they apply to the traffic’s “real” destination.
istiodestinationrule:
  enabled: false
  tls:
    mode: ISTIO_MUTUAL

# Whether to enable "istio-blackwhitelist" for external API access
istioblackwhitelist:
  enabled: false
  providerUrl: http://192.168.60.60:8080/WhiteList

# ========== Delete below section if not applicable =============  
# Below are SAMPLE configurable values working with configmap.yaml

dummy-props:
  mongodb:
    database: TEST_DB
    serverUrl: "ess99.wisers.com:10000"
    username:
    password:


# Dependent Chart Props Overridden
redis-dummy:
  enabled: false
  appName: redis-dummy
  imageRepository: ess-repos01.wisers.com:8888/redis
  imageTag: 3
  service:
    externalPort: 6379


# Dependent Chart Props Overridden
dummy-api:
  enabled: false
  
# ===================================================================
