fail_fast: true
repos:
  - repo: local
    hooks:
      - id: unittest
        name: unittest
        entry: bash -c 'cd tests && python -m unittest'
        language: system
        stages: [commit]
