repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: no-commit-to-branch
        args: [--branch, master, --branch, develop]
      - id: check-added-large-files
        args: [--maxkb=45000]
      - id: check-ast
        files: src/*
      # - id: mixed-line-ending
      # - id: end-of-file-fixer
      - id: requirements-txt-fixer
      # - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: forbid-new-submodules
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
      - id: flake8
        name: flake8
        args:
          - '--config=setup.cfg'
    #     name: flake8 except __init__.py
    #     language_version: python3.6
    #     args: # arguments to configure flake8
    #         # making isort line length compatible with black
    #         - "--max-line-length=128"
    #         - "--max-complexity=18"
    #         - "--select=B,C,E,F,W,T4,B9"
    #         - "--exclude=__init__.py,TGSAN.py,crf.py,cnn.py,src/inferlight/*"
    #         - "--extend-ignore=W605,E23,W291,W292"
    #     additional_dependencies: ["flake8-bugbear==20.1.4"]
    #   - id: flake8
    #     name: flake8 only __init__.py
    #     args:
    #       - "--extend-ignore=F401,W605,E23,W291,W292"
    #       - "--max-line-length=128"
    #     files: __init__.py
    # args: [--exclude=__init__.py]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.782
    hooks:
      - id: mypy
        language_version: python3.6
  - repo: local
    hooks:
      - id: unittest
        name: unittest
        entry: bash -c 'cd tests && python -m unittest'
        language: system
        stages: [commit]
