task: "chinese_word_segmentation"
device: 0
data:
  output_dir: "../config/examples/chinese_word_segmentation/BERT_CRF"
  data_dir: "../data/datasets/sample/chinese_word_segmentation"
  train: sample.json
  dev: sample.json
  test: sample.json
text_prepro:
  steps:
    - full_to_half
eval:
  batch_size: 64
  model_file: "model.pt" # under output_dir / "model"
train:
  model_class: "BERT_CRF"
  seed: 42
  batch_size: 16
  final_model: "best" # or "last"
  optimization_metric: "micro_f1"
  early_stop: null
model_params:
  # ================= TDBERT =================
  num_train_epochs: 2
  embedding_trainable: True
  tokenizer_name: "bert-base-chinese"  # source:::tokenizer_type "huggingface:::toastynews/electra-hongkongese-large-discriminator"
  pretrained_lm: "bert-base-chinese" # huggingface format "toastynews/electra-hongkongese-large-discriminator"
