task: "sequence_classification"
device: 0
data:
  output_dir: "../config/examples/sequence_classification/TEXT_CNN"
  data_dir: "../data/datasets/sample/sequence_classification"
  train: train_sample.json
  dev: test_sample.json
  test: test_sample.json
  unlabeled: unlabeled_sample.json
text_prepro:
  steps:
    - utf8_replace
    - simplified_chinese
    - lower_case
    - full_to_half
train:
  model_class: "TEXT_CNN"
  seed: 42
  batch_size: 6
  final_model: "best" # or "last"
  optimization_metric: "macro_f1"
  early_stop: null
eval:
  batch_size: 64
  model_file: "model.pt" # under output_dir / "model"
model_params:
  num_train_epochs: 2
  embedding_trainable: True