task: "target_classification"
device: 0
data:
  output_dir: "../config/examples/target_classification/TGSAN2"
  data_dir: "../data/datasets/sample/target_classification"
  train: sample.json
  dev: sample.json
  test: sample.json
text_prepro:
  steps:
    - simplified_chinese
    - lower_case
    - convert_java_index
train:
  model_class: "TGSAN2"
  seed: 42
  batch_size: 16
  final_model: "best" # or "last"
  optimization_metric: "macro_f1"
  early_stop: null
eval:
  batch_size: 64
  model_file: "model.pt" # under output_dir / "model"
model_params:
  num_train_epochs: 2