task: "target_classification"
device: 0
data:
  output_dir: "../config/examples/TGSAN"
  data_dir: "../data/datasets/sample/target_classification"
  train: sample.json 
  dev: sample.json 
  test: sample.json 
  labels: 3_ways # 2_ways
text_prepro:
  steps:
    - simplified_chinese
    - lower_case
    - convert_java_index
    # - extract_post_context_1
    # - extract_post_context_2
eval:
  batch_size: 64
  model_file: "model.pt" # under output_dir / "model"
train:
  model_class: "TGSAN"
  seed: 42
  batch_size: 16
  final_model: "best" # or "last"
  optimization_metric: "macro_f1"
  early_stop: null
eval:
  batch_size: 64
  model_file: "model.pt" # under output_dir / "model" 
  # ================= TDBERT =================
model_params:
  num_train_epochs: 10
  embedding_trainable: False
