train:
  output_dir: "20201208_TDBERT_DECOUPLE/decouple_rus_bal_dev44"
model:
  TDBERT:
    preprocess:
      sentence_length: 180
      text_preprocessing: "hk_beauty" # None, "", hk_beauty, ...
      lowercase: True
      lemmatize: True
      remove_separators: True
      mask_target: False
      tokenizer: "huggingface:::toastynews/electra-hongkongese-large-discriminator"  # source:::tokenizer_type "huggingface:::toastynews/electra-hongkongese-large-discriminator"   
    body:
      pretrained_lm: "toastynews/electra-hongkongese-large-discriminator" # huggingface format "toastynews/electra-hongkongese-large-discriminator" 
      target_pooling: "max"
      dropout_rate: 0.1
    optim:
      0:
        optimizer: "AdamW"
        sampler: "random"
        batch_size: 16
        learning_rate: 2e-5
        num_train_epochs: 20