name: bert_base_chinese
do_train: true
do_eval: true
model:
  TDBERT:
    preprocess:
      mask_target: false
      tokenizer_source: transformers
      tokenizer_name: bert-base-chinese      # source:::tokenizer_type "huggingface:::toastynews/electra-hongkongese-large-discriminator"   
    body:
      pretrained_lm: bert-base-chinese
      use_cls: false
    optim:
      num_train_epochs: 10
train:
  output_dir: light_bert_2/bert_base_chinese
