device: 0
data:
  model_dir: "../output/20210527_rolex_tdbert"
  data_dir: "rolex/data_0524"
  train: train.json 
  dev: dev.json 
  test: test.json 
text_prepro:
  steps:
    - simplified_chinese
    - lower_case
    - convert_java_index
    # - extract_post_context_1
    # - extract_post_context_2
eval:
  batch_size: 64
  state_file: "*.pt"
train:
  model_class: "TDBERT"
  seed: 42
  batch_size: 16
model_params:
  xxxxx: xxxxx
  max_length: 180
  # tokenizer_name: "bert_base_chinese"  # source:::tokenizer_type "huggingface:::toastynews/electra-hongkongese-large-discriminator"   
  # pretrained_lm: "bert_base_chinese" # huggingface format "toastynews/electra-hongkongese-large-discriminator" 


  


