task: "target_classification"
device: 1
data:
  output_dir: "../output/wbi/org_per_bert_avg_20211108"
  data_dir: "../data/datasets/internal/wbi_comb"
  train: test_non_ext.json
  dev: test_non_ext.json
  test: test_non_ext.json
  unlabeled: unlabeled.json
  extra_tokens: nan.json
text_prepro:
  steps:
    - concat_headline_content_with_sep
#     - concat_pub_code
#     - concat_entity_name
    - extract_post_context_1
    - simplified_chinese
    - full_to_half
eval:
  batch_size: 16
  model_file: "model.pt"
train:
  model_class: "TDBERT"
  kd:
    use_kd: False
    teacher_dir: "../output/post_sentiment_20210707_bert_avg/model"
    loss_type: 'mse'
    soft_lambda: 0.5
    kl_T: 5
  seed: 42
  log_steps: 100
  batch_size: 16
  final_model: "best" # "best" or "last"
  optimization_metric: "macro_f1" # "micro_f1" or "macro_f1"
  early_stop: null
model_params:
  # ================= TDBERT =================
  max_length: 256
  num_train_epochs: 10
  embedding_trainable: True
  output_hidden_act_func: "PReLU"
  output_hidden_dim: 128
  output_use_bn: False
  tokenizer_name: "hfl/chinese-macbert-base"  # voidful/albert_chinese_tiny
  pretrained_lm: "hfl/chinese-macbert-base" # voidful/albert_chinese_tiny
explanation:
    Random:
      method: "Random"