task: "sequence_classification"
device: 0
data:
  output_dir: "../output/sst/20220504_imdb_uda"
  data_dir: "../data/datasets/public/sequence_classification/imdb"
  train: train_uda.json
  dev: test.json
  test: test.json
  unlabeled: unlabeled_uda.json
  extra_special_tokens: 
    - unused5
  pad_in_collate: False
text_prepro:
  steps:
    - simplified_chinese
    - full_to_half
eval:
  batch_size: 16
  model_file: "model.pt"
train:
  model_class: "BERT_CLS"
  kd:
    use_kd: False
    teacher_dir: "../output/post_sentiment_20210707_bert_avg/model"
    loss_type: 'mse'
    soft_lambda: 0.5
    kl_T: 5
  uda:
    use_uda: True
    tsa: linear_schedule
    total_steps: 15000
    eval_steps: 1000
    uda_coeff: 1
    uda_confidence_thresh: 0.45
    uda_softmax_temp: 0.85
  seed: 42
  log_steps: 100
  batch_size: 8
  final_model: "best" # "best" or "last"
  optimization_metric: "macro_f1" # "micro_f1" or "macro_f1"
  early_stop: null
  r_drop_factor: 0.5
  enable_focal_loss: False
  focal_loss_gamma: 2
  focal_loss_reduction: mean
  enable_model_ema: False
  model_ema_alpha: 0.5
  model_ema_steps: 100
  enable_adversarial: False  # False
  adversarial_k: 3
  adversarial_param_names: [ 'pretrained_model.embeddings.']
model_params:
  # ================= TDBERT =================
  max_length: 256
  num_train_epochs: 8
  embedding_trainable: True
  # output_hidden_act_func: "PReLU"
  output_hidden_dim: 128
  output_use_bn: False
  tokenizer_name: "bert-base-cased"  # voidful/albert_chinese_tiny
  pretrained_lm: "bert-base-cased" # voidful/albert_chinese_tiny
  label_smoothing: 0
explanation:
    Random:
      method: "Random"