task: "sequence_classification"
device: 0
data:
  output_dir: "../output/post_sentiment_20210625_kd_bert_cnn"
  data_dir: "../data/datasets/post_sentiment"
  train: train.json 
  dev: test.json 
  test: test.json
  unlabeled: unlabeled.json 
text_prepro:
  steps:
    - utf8_replace
    - simplified_chinese
    - lower_case
    - full_to_half
eval:
  batch_size: 64
  model_file: "model.pt"
train:
  model_class: "TEXT_CNN"
  kd: 
    use_kd: True
    teacher_dir: "../output/post_sentiment_20210623_bert_avg/model"
    loss_type: 'mse'
    soft_lambda: 0.5
    kl_T: 5
  seed: 42
  batch_size: 16
  final_model: "best" # "best" or "last"
  optimization_metric: "macro_f1" # "micro_f1" or "macro_f1"
  early_stop: null
model_params:
  # ================= TDBERT =================
  num_train_epochs: 20
  embedding_trainable: True
  # tokenizer_name: "bert-base-chinese"  # source:::tokenizer_type "huggingface:::toastynews/electra-hongkongese-large-discriminator"   
  # pretrained_lm: "bert-base-chinese" # huggingface format "toastynews/electra-hongkongese-large-discriminator" 
  # ================= TGSAN =================
  # num_train_epochs: 50
  # pretrained_emb_path: "../data/word_embeddings/sgns.target.word-character.char1-2.dynwin5.thr10.neg5.dim300.iter5"
  # embedding_trainable: False
