model_class: "TGSAN"
grid_search: False
seed: 42
logging_steps: -1
state_file: ""
output_dir: "20210318/tgsan_rolex_no_kd" # 20201125_TDBERT_HK_BEAUTY_CLASS_IMBAL/nn2_s0_up 20201125_TDBERT_HK_BEAUTY_TEXT_PREP/text_prep_max_len_150
# model_class: "TGSAN"
# grid_search: False
# seed: 42
# logging_steps: -1
# state_file: ""
# output_dir: "20210310/tgsan_english_2" # 20201125_TDBERT_HK_BEAUTY_CLASS_IMBAL/nn2_s0_up 20201125_TDBERT_HK_BEAUTY_TEXT_PREP/text_prep_max_len_150

