device: 0
data:
  output_dir: "../config/examples/TGSAN_without_pretrained"
  data_dir: "../data/datasets/sample"
  train: sample.json 
  dev: sample.json 
  test: sample.json 
  labels: 3_ways # 2_ways
text_prepro:
  steps:
    - simplified_chinese
    - lower_case
    - convert_java_index
    # - extract_post_context_1
    # - extract_post_context_2
eval:
  batch_size: 64
  model_file: "model.pt" # under output_dir / "model"
train:
  model_class: "TGSAN"
  seed: 42
  batch_size: 16
  final_model: "best" # or "last"
model_params:
  # ================= TDBERT =================
  # num_train_epochs: 10
  # embedding_trainable: False
  # tokenizer_name: "bert-base-chinese"  # source:::tokenizer_type "huggingface:::toastynews/electra-hongkongese-large-discriminator"   
  # pretrained_lm: "bert-base-chinese" # huggingface format "toastynews/electra-hongkongese-large-discriminator" 
  # ================= TGSAN =================
  num_train_epochs: 2
  pretrained_emb_path: null
