device: 0
data:
  output_dir: "../config/examples/chinese_word_segmentation/BERT_CRF"
  data_dir: "../data/datasets/sample/chinese_word_segmentation"
  train: sample.json 
  dev: sample.json 
  test: sample.json 
text_prepro:
  steps:
    - full_to_half
eval:
  batch_size: 64
  model_file: "model.pt" # under output_dir / "model"
train:
  task: "chinese_word_segmentation"
  model_class: "BERT_CRF"
  seed: 42
  batch_size: 16
  final_model: "best" # or "last"
  optimization_metric: "micro_f1"
  early_stop: null
model_params:
  # ================= TDBERT =================
  num_train_epochs: 5
  embedding_trainable: True
