{{- $appName := .Values.appName -}}
apiVersion: apps/v1
kind: Deployment
metadata:
{{- template "commonMeta" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ $appName }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ $appName }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ $appName }}
        image: {{ .Values.imageRepository }}:{{ .Values.imageTag }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}

        # Change Accordingly ---------------
        env:
        - name: TZ
          value: "Asia/Hong_Kong"
        # ----------------------------------

        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        ports:
        - containerPort: {{ default 8080 .Values.service.internalPort }}

        # Change Accordingly ---------------
#        volumeMounts:
#        - name: configs
#          mountPath: "/ailab/conf/gunicorn.conf"
#          subPath: "gunicorn.conf"
#        - name: configs
#          mountPath: "/ailab/conf/logging.conf"
#          subPath: "logging.conf"
        # ----------------------------------

      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 6 }}
      {{- end }}
      # volumes:
      # - name: configs
      #   configMap:
      #     name: {{ $appName }}


      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
