{{- if .Values.istioingress.enabled -}}
{{- $appName := .Values.appName -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
{{- template "commonMeta" . }}
spec:
  hosts:
  - "*"
  gateways:
  - {{ $appName }}
  http:
  - match:
    - uri:
        prefix: /{{ .Release.Namespace }}/{{ $appName }}
    rewrite:
      uri: /
    route:
    - destination:
        port:
          number: {{ default 8080 .Values.istioingress.internalPort }}
        host: {{ $appName }}
{{- end -}}
