{{- if .Values.istiodestinationrule.enabled -}}
{{- $appName := .Values.appName -}}
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
{{- template "commonMeta" . }}
spec:
  host: {{ $appName }}
  trafficPolicy:
    tls:
      mode: {{ .Values.istiodestinationrule.tls.mode }}
{{- end -}}
