model_class: TDBERT
grid_search: false
seed: 42
logging_steps: -1
state_file: ''
output_dir: light_bert_2/bert_base_chinese                  # 20201125_TDBERT_HK_BEAUTY_CLASS_IMBAL/nn2_s0_up 20201125_TDBERT_HK_BEAUTY_TEXT_PREP/text_prep_max_len_150

